#main accounts token
mainToken = "NjYyMjIyMjcyNjMwNjIwMTkw.GOUwzG.voWbJW1_xnQEZtrd6f-bRF5VTjcrBmkMz3uo_w"
# claim the sniped nitros on main account, if false nitro will be claimed on whichever token sniped it
claimOnMain = true
# claims in queue.txt, you can't have claimOnMain and claimOnQueue set to true at same time.
claimOnQueue = false

# check messages on main account
snipeOnMain = true
#use alts to snipe
useAlts = true

#use proxies for invite scraper
useProxies = true

#Do you want to show off your successful snipes in our discord server?
sendSuccessWebhook = true
#remove Anonymous and put down your discord name+tag (for example: Jonko#1610)
#If we find out you put in someone else's name your license will be revoked!
successWebhookUsername = "YourMOM"

#snipe pastes
snipePastes = true
#save paste content
savePastes = false
#if snipe-pastes is true, the paste tools that are set to true will be sniped
#supported pastes:
#"safenote.co", "controlc.com", "commie.io", "vpaste.net",
#"ivpaste.com", "justpaste.it", "apaste.info", "ghostbin.com",
#"ghostbin.co", "secureshare.support", "1ty.me", "quickforget.com",
#"temp.pm", "privatty.com", "saltify.io", "onetimesecret.com", "revealit.me",
#"pastebin.com", "anonfiles.com", "hatebin.com", "gofile.io", "paste2.org",
#"slexy.org", "pastelink.net", "paste.org.ru", "dumpz.org",
#"heypasteit.com", "paste.centos.org", "paste.ee", "paste.ofcode.org",
#"justpaste.me"
pasteTools = [
  "safenote.co",
  "controlc.com",
  "commie.io",
  "vpaste.net",
  "ivpaste.com",
  "justpaste.it",
  "apaste.info",
  "ghostbin.com",
  "ghostbin.co",
  "secureshare.support",
  "1ty.me",
  "quickforget.com",
  "temp.pm",
  "privatty.com",
  "saltify.io",
  "onetimesecret.com",
  "revealit.me",
  "pastebin.com",
  "anonfiles.com",
  "hatebin.com",
  "gofile.io",
  "paste2.org",
  "slexy.org",
  "pastelink.net",
  "paste.org.ru",
  "dumpz.org",
  "heypasteit.com",
  "paste.centos.org",
  "paste.ee",
  "paste.ofcode.org",
  "justpaste.me"
]

#custom webhook sent after one a the following events
webhookGiveawayJoined = "https://discord.com/api/webhooks/996921877425565766/VIsoPSoeocxt1YsYsoECzCAq-Uh5bKhhn8_wFb3RX7N3hAtvMv3QbbPnJ8dSQw6I-bj6"
webhookSentGiveawayDM = "https://discord.com/api/webhooks/996921967309488209/KfjPE8VQieHnAvgQ7LKqD62C94k2v7Hjstkp9IDPMdqjRmzZL5XEhPy-jN1BwD_Q0Wr3"
webhookGiveawayWon = "https://discord.com/api/webhooks/996922067574325288/YgOIWOvWH7wqkHsvfuF7KZD2d37H2UAVKUjSVP3645Ud-p3iG0g-QO12I6QO2N07lwEf"
webhookNitroFailed = "https://discord.com/api/webhooks/996922261707685978/hyC3z5-GIDiI17KktF9OBs8L4EOQiK9b5tx-w6pQlu_4DE3Vp_GMdgh5DCoM1sWyegEu"
webhookNitroClaimed = "https://discord.com/api/webhooks/996922342330618008/VfjOU0EFl7JLdRB5Qinx5Dc_NNH_l89nJg03CdHyMpWD9lsXf2b80xudo4FpxkbkmQxA"

#activate invite scraper
scrapeInvites = true
#checks invite and gets the invite's server's name (recommended to set as false)
captureInvites = false
#show scraped invites
showScrapedInvites = true
#save scraped invites
saveScrapedInvites = true

#join giveaways
joinGiveaways = true
#join giveaways on alts only
joinGiveawaysAltsOnly = true
#join giveaways after this many seconds, 0 for instant
joinGiveawaysDelay = 25
#auto claim giveaway
autoClaimGiveaway = true
#auto claim delay, will send message after this many seconds
autoClaimDelay = 15
#auto claim giveaway message
autoclaimGiveawayMessage = "hey i won the giveaway"
#dont join giveaways that contain these words
blacklistWordsGiveaway = ["ban","sniper/selfbot", "test","sniper","selfbot"]
#ONLY join giveaways that contain these words (case insensitive)
whitelistWordsGiveaway = ["nitro"]

#if removeDuplicates=true, nitro codes will be saved and won't be checked again
removeDuplicates = true
showDuplicates = true

showFakes = true #shows fake nitros in the console

#Optical Character Recognition, will snipe nitro code in images
OCR = false
#will snipe nitro code in QRCodes
QRCode = false

# if saveDuplicateGuild=true, it will ask you if you want leave duplicate guilds on alts on start
saveDuplicateGuilds = false

# type .stats in any channel to see sniper stats
webhookStats = true
# Send stats to this webhook
webhookStatsLink = "https://discord.com/api/webhooks/996923089210322944/OuPehkMc73l7gOo6E18Ng-zVZdV5AKx-2KnpymktWOrvan4RlLHAzwo6b3Z176u_VOqH"
# Custom stat command
webhookStatsCommand = ".stats"

# Try to redeem words that looks like Nitro gift code
smartSnipe = true

# Will snipe gift link in txt file
snipeInTxt = true

antiSpam = true
